'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { Download, MapPinned } from 'lucide-react';
import AppShell from '@/components/AppShell';
import MapView from '@/components/MapView';
import { EmptyState } from '@/components/FeedbackProvider';

type Detail = { project: Record<string, string | number | null>; reports: Array<Record<string, string | number | null>>; stats: { total: number; open: number; closed: number } };
export default function ProjectDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const [data, setData] = useState<Detail | null>(null); const [error, setError] = useState(''); const [id, setId] = useState('');
  const load = async (projectId: string) => { try { const response = await fetch(`/api/projects/${encodeURIComponent(projectId)}`); const body = await response.json(); if (!response.ok) throw new Error(body.message); setData(body); } catch (reason) { setError(reason instanceof Error ? reason.message : 'تعذر تحميل المشروع'); } };
  useEffect(() => { let active = true; void params.then(({ id: projectId }) => { if (active) { setId(projectId); void load(projectId); } }); return () => { active = false; }; }, [params]);
  if (error) return <AppShell><section className="error-state"><h1>{error}</h1><button className="btn primary" onClick={() => { setError(''); if (id) void load(id); }}>إعادة المحاولة</button></section></AppShell>;
  if (!data) return <AppShell><section className="loading-screen"><span className="skeleton-block" />جارٍ تحميل تفاصيل المشروع…</section></AppShell>;
  const project = data.project;
  return <AppShell><div className="space-y-5" dir="rtl"><header className="dashboard-hero flex flex-wrap items-center justify-between gap-4 p-6"><div><p className="text-sm text-blue-100/80">مرجع المشروع · <bdi>{String(project.operational_number)}</bdi></p><h1 className="mt-2 text-2xl font-black text-white">{String(project.name)}</h1><p className="mt-2 text-sm text-blue-100/80">المقاول: {String(project.contractor_name || 'غير محدد')} · الحالة: {String(project.status) === 'ACTIVE' ? 'جارٍ' : String(project.status)}</p></div><a className="btn secondary" href={`/api/export/kmz/${encodeURIComponent(id)}`} download><Download size={17} /> تصدير KMZ</a></header><section className="grid gap-4 sm:grid-cols-3">{[['إجمالي البلاغات', data.stats.total], ['المفتوح', data.stats.open], ['تمت المعالجة', data.stats.closed]].map(([label, value]) => <article key={String(label)} className="metric-card surface p-5"><p className="text-sm text-slate-500">{label}</p><strong className="mt-2 block text-3xl text-blue-900">{Number(value).toLocaleString('ar-SA')}</strong></article>)}</section><section className="surface overflow-hidden"><div className="flex items-center gap-2 border-b border-slate-200/70 p-5"><MapPinned size={20} className="text-blue-600" /><h2 className="font-bold">حدود المشروع وبلاغاته المرتبطة</h2></div><MapView query={`project_id=${encodeURIComponent(id)}`} onSelect={() => {}} /></section><section className="surface overflow-hidden"><h2 className="border-b border-slate-200/70 p-5 font-bold">البلاغات المرتبطة بالمشروع ({data.reports.length})</h2>{data.reports.length ? <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead className="bg-slate-100/70"><tr>{['رقم البلاغ', 'الحالة', 'الحي', 'الشارع', 'التاريخ'].map((h) => <th className="p-4 text-start" key={h}>{h}</th>)}</tr></thead><tbody>{data.reports.map((row, index) => <tr className={`border-t border-slate-100 ${index % 2 ? 'bg-slate-50/50' : ''}`} key={String(row.id)}><td className="p-4 font-bold text-blue-700"><bdi>{String(row.source_reference)}</bdi></td><td className="p-4">{String(row.source_status)}</td><td className="p-4">{String(row.district_raw || 'غير محدد')}</td><td className="p-4">{String(row.street_raw || 'غير محدد')}</td><td className="p-4">{String(row.reported_date || 'غير محدد')}</td></tr>)}</tbody></table></div> : <EmptyState title="لا توجد بلاغات مرتبطة" description="لم يتم العثور على بلاغات مصنفة داخل نطاق هذا المشروع." />}</section><Link className="btn secondary" href="/projects">العودة إلى مرجع المشاريع</Link></div></AppShell>;
}
